name: ZAP Scan

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
    paths:
    - .github/workflows/zap-scan.yml

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files
      run: tree -a -I 'venv|__pycache__|.git|.nova|.DS_Store|.pytest_cache|node_modules|.next|archive|scratch|target'

    - name: Copy ZAP rules
      run: cp zap/rules.json /home/runner/work/security/security/rules.json

    - name: Verify ZAP rules file
      run: ls -l /home/runner/work/security/security/rules.json

    - name: ZAP Full Scan
      id: zap_scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: ${{ secrets.WEBSITE_TARGET }}
        rules_file_name: './rules.json'
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        cmd_options: '-config log.level=DEBUG'
        allow_issue_writing: true
        mount_options: |
          -v /home/runner/work/security/security:/zap/wrk
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}



    - name: Verify Changed files
      id: verify-changed-files
      uses: tj-actions/verify-changed-files@v20
     # with:
       # files: |
       #   reports/*

    - name: Commit and Push Changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Updated Link Test Results
        branch: main
       #file_pattern: |
        #  reports/*
      env:
        GIT_USER_NAME: ${{ secrets.USER_NAME }}
        GIT_USER_EMAIL: ${{ secrets.USER_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
